version: '3.8'
# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  coreai-mcu-documents:
    build:
      target: development
    image: coreai-mcu-documents-development
    container_name: coreai-mcu-documents-development
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - coreai-mcu-documents-azurite
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
    environment: 
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING:-true}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT:-test}

  coreai-mcu-documents-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "${CORE_AI_DOCUMENTS_BLOB_PORT:-10000}:10000"
    volumes:
      - azurite_data:/data

volumes:
  azurite_data:
