services:
  coreai-mcu-documents:
    build:
      context: .
      target: production
    image: coreai-mcu-documents
    container_name: coreai-mcu-documents
    depends_on:
      - coreai-mcu-documents-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: coreai-mcu-documents-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  coreai-mcu-documents-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: coreai-mcu-documents
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
      AZURE_STORAGE_CONNECTION_STRING: 'SOME VALUE'
