services:
  coreai-mcu-documents:
    build:
      context: .
      target: production
    image: coreai-mcu-documents
    container_name: coreai-mcu-documents
    depends_on:
      - coreai-mcu-documents-azurite
    environment:
      APPINSIGHTS_CLOUDROLE: coreai-mcu-documents-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT:-test}

  coreai-mcu-documents-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
